# Seq2seq + Attention

1. 여러 Attention 모듈을 구현합니다.
2. 기존 Seq2seq 모델과의 차이를 이해합니다.

## 라이브러리

In [1]:
from tqdm import tqdm
from torch import nn
from torch.nn.utils.rnn import pad_packed_sequence, pack_padded_sequence
from torch.nn import functional as F

import torch
import random

## 데이터 전처리

데이터 처리는 이전과 동일

In [2]:
vocab_size = 100
pad_id = 0
sos_id = 1
eos_id = 2

src_data = [
  [3, 77, 56, 26, 3, 55, 12, 36, 31],
  [58, 20, 65, 46, 26, 10, 76, 44],
  [58, 17, 8],
  [59],
  [29, 3, 52, 74, 73, 51, 39, 75, 19],
  [41, 55, 77, 21, 52, 92, 97, 69, 54, 14, 93],
  [39, 47, 96, 68, 55, 16, 90, 45, 89, 84, 19, 22, 32, 99, 5],
  [75, 34, 17, 3, 86, 88],
  [63, 39, 5, 35, 67, 56, 68, 89, 55, 66],
  [12, 40, 69, 39, 49]
]

trg_data = [
  [75, 13, 22, 77, 89, 21, 13, 86, 95],
  [79, 14, 91, 41, 32, 79, 88, 34, 8, 68, 32, 77, 58, 7, 9, 87],
  [85, 8, 50, 30],
  [47, 30],
  [8, 85, 87, 77, 47, 21, 23, 98, 83, 4, 47, 97, 40, 43, 70, 8, 65, 71, 69, 88],
  [32, 37, 31, 77, 38, 93, 45, 74, 47, 54, 31, 18],
  [37, 14, 49, 24, 93, 37, 54, 51, 39, 84],
  [16, 98, 68, 57, 55, 46, 66, 85, 18],
  [20, 70, 14, 6, 58, 90, 30, 17, 91, 18, 90],
  [37, 93, 98, 13, 45, 28, 89, 72, 70]
]

In [3]:
trg_data = [[sos_id]+seq+[eos_id] for seq in tqdm(trg_data)]

100%|██████████| 10/10 [00:00<00:00, 143150.31it/s]


In [5]:
def padding(data, is_src=True):
    max_len = len(max(data, key=len))
    print(f"Maximum sequence length: {max_len}")

    valid_lens = []
    for i, seq in enumerate(tqdm(data)):
        valid_lens.append(len(seq))
        if len(seq) < max_len:
            data[i] = seq + [pad_id] * (max_len - len(seq))

    return data, valid_lens, max_len

In [6]:
src_data, src_lens, src_max_len = padding(src_data)
trg_data, trg_lens, trg_max_len = padding(trg_data)

100%|██████████| 10/10 [00:00<00:00, 133152.51it/s]

Maximum sequence length: 15
Maximum sequence length: 22


In [7]:
# B: batch size, S_L: source maximum sequence length, T_L: target maximum sequence length
src_batch = torch.LongTensor(src_data)  # (B, S_L)
src_batch_lens = torch.LongTensor(src_lens)  # (B)
trg_batch = torch.LongTensor(trg_data)  # (B, T_L)
trg_batch_lens = torch.LongTensor(trg_lens)  # (B)

print(src_batch.shape)
print(src_batch_lens.shape)
print(trg_batch.shape)
print(trg_batch_lens.shape)

torch.Size([10, 15])
torch.Size([10])
torch.Size([10, 22])
torch.Size([10])


In [8]:
src_batch_lens, sorted_idx = src_batch_lens.sort(descending=True)
src_batch = src_batch[sorted_idx]
trg_batch = trg_batch[sorted_idx]
trg_batch_lens = trg_batch_lens[sorted_idx]

print(src_batch)
print(src_batch_lens)
print(trg_batch)
print(trg_batch_lens)

tensor([[39, 47, 96, 68, 55, 16, 90, 45, 89, 84, 19, 22, 32, 99,  5],
        [41, 55, 77, 21, 52, 92, 97, 69, 54, 14, 93,  0,  0,  0,  0],
        [63, 39,  5, 35, 67, 56, 68, 89, 55, 66,  0,  0,  0,  0,  0],
        [ 3, 77, 56, 26,  3, 55, 12, 36, 31,  0,  0,  0,  0,  0,  0],
        [29,  3, 52, 74, 73, 51, 39, 75, 19,  0,  0,  0,  0,  0,  0],
        [58, 20, 65, 46, 26, 10, 76, 44,  0,  0,  0,  0,  0,  0,  0],
        [75, 34, 17,  3, 86, 88,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [12, 40, 69, 39, 49,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [58, 17,  8,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [59,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0]])
tensor([15, 11, 10,  9,  9,  8,  6,  5,  3,  1])
tensor([[ 1, 37, 14, 49, 24, 93, 37, 54, 51, 39, 84,  2,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0],
        [ 1, 32, 37, 31, 77, 38, 93, 45, 74, 47, 54, 31, 18,  2,  0,  0,  0,  0,
          0,  0,  0,  0],
        [ 1, 20, 70, 14,  6, 58, 90,

## Encoder 구현

이전 Seq2seq 와 동일

In [9]:
embedding_size = 256
hidden_size = 512
num_layers = 2
num_dirs = 2
dropout = 0.1

In [11]:
class Encoder(nn.Module):
    def __init__(self):
        super(Encoder, self).__init__()

        self.embedding = nn.Embedding(vocab_size, embedding_size)
        self.gru = nn.GRU(
            input_size=embedding_size, 
            hidden_size=hidden_size,
            num_layers=num_layers,
            bidirectional=True if num_dirs > 1 else False,
            dropout=dropout
        )
        self.linear = nn.Linear(num_dirs * hidden_size, hidden_size)

    def forward(self, batch, batch_lens):  # batch: (B, S_L), batch_lens: (B)
        # d_w: word embedding size
        batch_emb = self.embedding(batch)  # (B, S_L, d_w)
        batch_emb = batch_emb.transpose(0, 1)  # (S_L, B, d_w)

        packed_input = pack_padded_sequence(batch_emb, batch_lens)

        h_0 = torch.zeros((num_layers * num_dirs, batch.shape[0], hidden_size))  # (num_layers*num_dirs, B, d_h) = (4, B, d_h)
        packed_outputs, h_n = self.gru(packed_input, h_0)  # h_n: (4, B, d_h)
        outputs = pad_packed_sequence(packed_outputs)[0]  # outputs: (S_L, B, 2d_h)
        outputs = torch.tanh(self.linear(outputs))  # (S_L, B, d_h)

        forward_hidden = h_n[-2, :, :]
        backward_hidden = h_n[-1, :, :]
        hidden = torch.tanh(self.linear(torch.cat((forward_hidden, backward_hidden), dim=-1))).unsqueeze(0)  # (1, B, d_h)

        return outputs, hidden

In [12]:
encoder = Encoder()

## Dot-product Attention 구현

대표적인 Attention 형태 중 하나인 Dot-product Attention

In [14]:
class DotAttention(nn.Module):
    def __init__(self):
        super().__init__()
        
    def forward(self, decoder_hidden, encoder_outputs): 
        #(1,B,d_h), (S_L, B, d_h)
        query = decoder_hidden.squeeze(0) # (B, d_h)
        key = encoder_outputs.transpose(0,1) # (B, S_L, d_h)
        
        energy = torch.sum(torch.mul(key, query.unsqueeze(1)), dim=-1)
        # (B, S_L)
        
        attn_scores = F.softmax(energy, dim=-1) # (B, S_L)
        attn_values = torch.sum(torch.mul(encoder_outputs.transpose(0,1),
                                          attn_scores.unsqueeze(2)), dim=1)
        # (B, d_h)
        
        return attn_values, attn_scores

In [15]:
dot_attn = DotAttention()

이제 이 attention 모듈을 가지는 Decoder 클래스를 구현하겠습니다.

In [16]:
class Decoder(nn.Module):
    def __init__(self, attention): # attention
        super().__init__()
        
        self.embedding = nn.Embedding(vocab_size, embedding_size)
        self.attention = attention
        self.rnn = nn.GRU(
             embedding_size,
             hidden_size
        )
        self.output_linear = nn.Linear(2*hidden_size, vocab_size)
        
    def forward(self, batch, encoder_outputs, hidden): 
        # batch: (B), encoder_outputs : (L, B, d_h), hidden : (1, B, d_h)
        batch_emb = self.embedding(batch)
        batch_emb = batch_emb.unsqueeze(0) # (1, B, d_w)
        
        outputs, hidden = self.rnn(batch_emb, hidden)
        # (1, B, d_h) , (1, B, d_h)
        
        attn_values, attn_scores = self.attention(hidden, encoder_outputs)
        # (B, d_h), (B, S_L)
        concat_outputs = torch.cat((outputs, attn_values.unsqueeze(0)), dim = -1) 
        # (1, B, 2d_h)
        return self.output_linear(concat_outputs).squeeze(0), hidden
        # (B, V), (1, B, d_h)

In [17]:
decoder = Decoder(dot_attn)

## Seq2seq 모델 구축

In [19]:
class Seq2seq(nn.Module):
    def __init__(self, encoder, decoder):
        super(Seq2seq, self).__init__()

        self.encoder = encoder
        self.decoder = decoder

    def forward(self, src_batch, src_batch_lens, trg_batch, teacher_forcing_prob=0.5):
    # src_batch: (B, S_L), src_batch_lens: (B), trg_batch: (B, T_L)

        encoder_outputs, hidden = self.encoder(src_batch, src_batch_lens)  # encoder_outputs: (S_L, B, d_h), hidden: (1, B, d_h)

        input_ids = trg_batch[:, 0]  # (B)
        batch_size = src_batch.shape[0]
        outputs = torch.zeros(trg_max_len, batch_size, vocab_size)  # (T_L, B, V)

        for t in range(1, trg_max_len):
            decoder_outputs, hidden = self.decoder(input_ids, encoder_outputs, hidden)  # decoder_outputs: (B, V), hidden: (1, B, d_h)

            outputs[t] = decoder_outputs
            _, top_ids = torch.max(decoder_outputs, dim=-1)  # top_ids: (B)

            input_ids = trg_batch[:, t] if random.random() > teacher_forcing_prob else top_ids

        return outputs

In [20]:
seq2seq = Seq2seq(encoder, decoder)

## 모델 사용해보기

In [21]:
# V: vocab size
outputs = seq2seq(src_batch, src_batch_lens, trg_batch)  # (T_L, B, V)

print(outputs)
print(outputs.shape)

tensor([[[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
           0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
           0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
           0.0000e+00,  0.0000e+00],
         ...,
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
           0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
           0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
           0.0000e+00,  0.0000e+00]],

        [[ 1.1856e-01,  1.0816e-01,  1.3034e-02,  ..., -1.4176e-01,
           1.0259e-01,  1.6374e-01],
         [ 1.4788e-01,  1.1311e-01,  1.9207e-04,  ..., -1.1806e-01,
           1.0833e-01,  1.1973e-01],
         [ 1.6875e-01,  6.9487e-02,  1.4208e-02,  ..., -1.2804e-01,
           9.5588e-02,  1.6005e-01],
         ...,
         [ 1.2274e-01,  1

In [25]:
sample_sent = [4, 10, 88, 46, 72, 34, 14, 51]
sample_len = len(sample_sent)

sample_batch = torch.LongTensor(sample_sent).unsqueeze(0)  # (1, L)
sample_batch_len = torch.LongTensor([sample_len])  # (1)

encoder_output, hidden = seq2seq.encoder(sample_batch, sample_batch_len)  # hidden: (4, 1, d_h)

In [26]:
input_id = torch.LongTensor([sos_id]) # (1)
output = []

for t in range(1, trg_max_len):
    decoder_output, hidden = seq2seq.decoder(input_id, encoder_output, hidden)  # decoder_output: (1, V), hidden: (4, 1, d_h)

    _, top_id = torch.max(decoder_output, dim=-1)  # top_ids: (1)

    if top_id == eos_id:
        break
    else:
        output += top_id.tolist()
        input_id = top_id

In [27]:
print(output)

[88, 98, 24, 74, 12, 96, 73, 13, 13, 23, 94, 62, 72, 56, 13, 13, 94, 61, 80, 80, 25]


## Concat Attention 구현

Bahdanau Attention 이라고도 불리는 Concat Attention 을 구현해보자
* `self.w` : Concat 한 query 와 key 벡터를 1차적으로 linear transformation
* `self.v` : Attention logit 값을 계산

In [28]:
class ConcatAttention(nn.Module):
    def __init__(self):
        super().__init__()

        self.w = nn.Linear(2*hidden_size, hidden_size, bias=False)
        self.v = nn.Linear(hidden_size, 1, bias=False)

    def forward(self, decoder_hidden, encoder_outputs):  # (1, B, d_h), (S_L, B, d_h)
        src_max_len = encoder_outputs.shape[0]

        decoder_hidden = decoder_hidden.transpose(0, 1).repeat(1, src_max_len, 1)  # (B, S_L, d_h)
        encoder_outputs = encoder_outputs.transpose(0, 1)  # (B, S_L, d_h)

        concat_hiddens = torch.cat((decoder_hidden, encoder_outputs), dim=2)  # (B, S_L, 2d_h)
        energy = torch.tanh(self.w(concat_hiddens))  # (B, S_L, d_h)

        attn_scores = F.softmax(self.v(energy), dim=1)  # (B, S_L, 1)
        attn_values = torch.sum(torch.mul(encoder_outputs, attn_scores), dim=1)  # (B, d_h)

        return attn_values, attn_scores

In [29]:
concat_attn = ConcatAttention()

In [30]:
class Decoder(nn.Module):
    def __init__(self, attention):
        super().__init__()

        self.embedding = nn.Embedding(vocab_size, embedding_size)
        self.attention = attention
        self.rnn = nn.GRU(
            embedding_size + hidden_size,
            hidden_size
        )
        self.output_linear = nn.Linear(hidden_size, vocab_size)

    def forward(self, batch, encoder_outputs, hidden):  # batch: (B), encoder_outputs: (S_L, B, d_h), hidden: (1, B, d_h)  
        batch_emb = self.embedding(batch)  # (B, d_w)
        batch_emb = batch_emb.unsqueeze(0)  # (1, B, d_w)

        attn_values, attn_scores = self.attention(hidden, encoder_outputs)  # (B, d_h), (B, S_L)

        concat_emb = torch.cat((batch_emb, attn_values.unsqueeze(0)), dim=-1)  # (1, B, d_w+d_h)

        outputs, hidden = self.rnn(concat_emb, hidden)  # (1, B, d_h), (1, B, d_h)

        return self.output_linear(outputs).squeeze(0), hidden  # (B, V), (1, B, d_h)

In [31]:
decoder = Decoder(concat_attn)

In [32]:
seq2seq = Seq2seq(encoder, decoder)

In [33]:
outputs = seq2seq(src_batch, src_batch_lens, trg_batch)

print(outputs)
print(outputs.shape)

tensor([[[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
         ...,
         [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]],

        [[-0.0030,  0.0956, -0.1299,  ..., -0.0355, -0.0080, -0.0551],
         [ 0.0432,  0.0365, -0.1335,  ...,  0.0048,  0.0124, -0.0232],
         [ 0.0764,  0.0957, -0.1184,  ..., -0.0396,  0.0017, -0.0469],
         ...,
         [ 0.0333,  0.0686, -0.1385,  ..., -0.0049, -0.0621, -0.0433],
         [ 0.0160,  0.1058, -0.1270,  ..., -0.0233,  0.0085, -0.0530],
         [ 0.0372,  0.0892, -0.1486,  ..., -0.0234,  0.0236, -0.0206]],

        [[ 0.0332,  0.1695, -0.2200,  ..., -0.0126,  0.0953, -0.0379],
         [ 0.0662,  0.1333, -0.2168,  ...,  0